name: golangci-lint
on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: "*"

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        golang:
          - 1.18
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.1.0
        with:
          version: v1.46.1
          args: --timeout=10m
          skip-go-installation: true
