name: golangci-lint

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ "*" ]

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          # go-version: '1.24'

          cache: true

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          # version: v1.64.8

          args: --timeout=10m --out-format=colored-line-number

          # skip-dirs: vendor,docs