name: Nemo CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    name: ${{ matrix.os }} - Go ${{ matrix.go_version }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        go_version:
          - '1.24'
        os:
          - ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go ${{ matrix.go_version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go_version }}
          # go-version-file: go.mod

          cache: true

      - name: Get dependencies and tidy
        run: |
          make tidy
        env:
          GOPROXY: "https://proxy.golang.org,direct"

      - name: Check code formatting (gofmt)
        run: |
          FILES=$(gofmt -l .)
          if [ -n "$FILES" ]; then
            echo "The following files are not formatted correctly:"
            echo "$FILES"
            echo "Please run 'go fmt ./...' locally and commit the changes."
            exit 1
          fi
          echo "All files are formatted correctly."

      - name: Run tests
        run: |
          make test
        env:
          CGO_ENABLED: 0